services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  worker-downloader:
    build:
      context: ./worker-downloader
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./downloads:/downloads
      - ./worker-downloader:/app
      - /app/node_modules
    environment:
      - REDIS_HOST=redis
      - DOCKER_DOWNLOADS_PATH=${PWD}/downloads
    command: npm run dev
    restart: always

  app-downloader:
    build:
      context: ./app-downloader
      target: development
    depends_on:
      - redis
    ports:
      - "5173:5173"
    volumes:
      - ./app-downloader:/app
      - /app/node_modules
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=development
    command: npm run dev
    restart: always
